apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: controller
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: controller
      {{- include "labels" . | nindent 6 }}
  replicas: {{ .Values.controller.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: controller
       {{- include "labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #image: ghcr.io/kore3lab/kore-controller:{{ .Chart.AppVersion }}
        image: honester/kore-controller:{{ .Chart.AppVersion }}
        #args:
        #- --leader-elect
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- if .Values.controller.resources }}
        resources: {{- toYaml .Values.controller.resources | nindent 12 }}
        {{- end }}
      serviceAccountName: {{ .Chart.Name }}
      terminationGracePeriodSeconds: 10
